import type { Metadata } from "next";
import {  Oswald } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar/Navbar";
import Footer from "@/component/footer/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const osWald = Oswald({
   variable: "--font-oswald",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="dark"
      className={`${osWald.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#000000]">

        <Navbar/>
        
        {children}

        <Footer/>
        
        
        </body>
    </html>
  );
}
